INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'User.firstName', 'templateFields', 1);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'User.lastName', 'templateFields', 2);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'InvestmentOpportunity.name', 'templateFields', 3);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'InvestmentOpportunity.carry', 'templateFields', 4);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Investment.amount', 'templateFields', 5);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'User.profileType', 'templateFields', 6);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Applied', 'investmentStatus', 1);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Approved', 'investmentStatus', 2);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Doc Sent to Investor', 'investmentStatus', 3);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Doc Signed By Investor', 'investmentStatus', 4);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Funds Transfer Initiated', 'investmentStatus', 5);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Funds Received', 'investmentStatus', 6);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Investment Completed', 'investmentStatus', 7);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Doc Signed By Vibhu', 'investmentStatus', 8);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Closed', 'investmentStatus', 9);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Initiate Refund', 'refundStatus', 1);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Refund Received', 'refundStatus', 2);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Qualified Purchaser - Net worth of at least $5 Million', 'accreditation', 1);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Qualified Client - Net worth of at least $2.2 Million excluding primary home', 'accreditation', 2);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Accredited Investor - Net worth of at least $1 Million excluding primary home', 'accreditation', 3);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Accredited Investor - Joint Income $300,000 each year for last two years', 'accreditation', 4);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Accredited Investor - Individual Income $200,000 each year for last two years', 'accreditation', 5);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'Accredited Investor - meet other criteria set by SEC', 'accreditation', 6);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'An entity where all owners meet one of the criteria above', 'accreditation', 7);
INSERT INTO MasterData (active, createdAt, updatedAt, value, type, `order`) VALUES (1, NOW(), NOW(), 'None of the above', 'accreditation', 8);