CREATE TABLE `InvestmentDocument` (
  `id` int NOT NULL AUTO_INCREMENT,
  `companyId` int NOT NULL,
  `userId` int NOT NULL,
  `investmentOpportunityId` int NOT NULL,
  `templateId` int DEFAULT NULL,
  `financialYear` int DEFAULT NULL,
  `folder` varchar(255) DEFAULT NULL,
  `docLink` varchar(255) DEFAULT NULL,
  `templateName` varchar(255) DEFAULT NULL,
  `templateType` varchar(255) DEFAULT NULL,
  `uploadedBy` int DEFAULT NULL,
  `uploadedDate` datetime DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`doucmentId`),
  KEY `companyId` (`companyId`),
  KEY `userId` (`userId`),
  KEY `investmentOpportunityId` (`investmentOpportunityId`),
  CONSTRAINT `fk_companyId` FOREIGN KEY (`companyId`) REFERENCES `Company` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_investmentOpportunityId` FOREIGN KEY (`investmentOpportunityId`) REFERENCES `InvestmentOpportunity` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_userId` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
